### ISSUE TITLE
Add support for reading table/column comments

### ISSUE THREAD

**Issue by rgalanakis** [jeremyevans/sequel-annotate#11]
Thanks for making this gem (and Sequel of course)! I hope it's not out of bounds to make a feature request.

Something I think would be nice to add is the ability to include table and column comments (`COMMENT ON TABLE mytable IS 'This is my table.';`) (and maybe comments from other types) in the annotations. Documenting a class in Ruby code is easy enough, but it's not always clear where the docs for column should live since it may not even be referred to with a method declaration. Columns would be the most helpful but I think index comments could be pretty useful too, to explain what access pattern they are intended to support.

If this isn't a priority to add, is it a thing you'd merge if given a PR (the code here is marvelously simple so I should be able to whip something up eventually though it may be a while). Thanks again!

**Comment by jeremyevans** [comment]
I think this is a worthwhile feature, and I would accept a PR for it.  I'm going to close this now, but please submit a PR if you would like this added.
