### ISSUE TITLE
Models backed by a complex dataset fail with exception

### ISSUE THREAD

**Issue by adam12** [jeremyevans/sequel-annotate#17]
When backing a model with a dataset that's been derived but fairly modified from a table, the annotation process fails with an exception:

<details>
<pre>
NoMethodError: undefined method `length' for nil:NilClass
    /app/lib/sequel/annotate.rb:123:in `block (2 levels) in align'
    /app/lib/sequel/annotate.rb:122:in `each'
    /app/lib/sequel/annotate.rb:122:in `block in align'
    /app/lib/sequel/annotate.rb:121:in `times'
    /app/lib/sequel/annotate.rb:121:in `align'
    /app/lib/sequel/annotate.rb:256:in `schema_comment_columns'
    /app/lib/sequel/annotate.rb:94:in `schema_comment'
    /app/lib/sequel/annotate.rb:60:in `annotate'
    /app/lib/sequel/annotate.rb:23:in `block in annotate'
    /app/lib/sequel/annotate.rb:15:in `each'
    /app/lib/sequel/annotate.rb:15:in `annotate'
    spec/sequel-annotate_spec.rb:328:in `block (4 levels) in <main>'
    spec/sequel-annotate_spec.rb:327:in `times'
    spec/sequel-annotate_spec.rb:327:in `block (3 levels) in <main>'
</pre>
</details>

I'm not sure if we can actually annotate these types of models safely. I've got some [work started here](https://github.com/jeremyevans/sequel-annotate/compare/master...adam12:complex-datasets) which recreates the issue but haven't been able to find a solve.

Alternatively, I'm submitting a PR which allows skipping of files using a magic comment.

**Comment by jeremyevans** [comment]
I think if you can recreate the issue in a failing test, that should be enough for me.  I'll probably just have it skip the commenting of such models (possibly with a warning).

**Comment by jeremyevans** [comment]
Fixed by 10aeb1db43786e3bd73e0c4cd9bfb35c78c390fb
