### ISSUE TITLE
Example rake task in README.md doesn't work

### ISSUE THREAD

**Issue by clthck** [jeremyevans/sequel-annotate#2]

**Comment by jeremyevans** [comment]
With no backtrace or really any information at all, it's hard to help.  If I had to guess, you aren't loading your Sequel::Database object, so loading your model class fails.  Can you provide some more information or a backtrace?

**Comment by clthck** [comment]
Sorry for providing no description. You're right. It says `uninitialized constant Post`, which means Sequel::Model classes are not loaded. But I don't know how to do it.

**Comment by jeremyevans** [comment]
Again, it's hard to tell without a backtrace, but if I had to guess, you are referencing Post before Post is defined.  If your project is open source, you can provide a link to it.  Otherwise, it's probably not something I can help with.  Note that the example rake task in the README is just that, an example, the idea is you would modify it to fit your application.

**Comment by clthck** [comment]
`lib/tasks/annotate.rake`
```
desc "Update model annotations"
task :annotate do
  require 'sequel/annotate'
  Sequel::Annotate.annotate(Dir['models/Post.rb'])
end
```

This didn't output any error. And it did nothing. So I changed `models/Post.rb` to `app/models/Post.rb` and tried again. (`bundle exec rake annotate`)
Now it throws an error, saying `uninitialized constant Post` as aforementioned.

Here's the backtrace.
```
rake aborted!
NameError: uninitialized constant Post
/Volumes/WORKS/Web Applications/herokuapps/bone-falcon/lib/tasks/annotate.rake:4:in `block in <top (required)>'
Tasks: TOP => annotate
(See full trace by running task with --trace)
```

**Comment by jeremyevans** [comment]
Not outputing an error if the file name doesn't exist is expected, since `Dir.[]` would return an empty array in that case.

You probably want to run rake with `rake -t` to get the full backtrace, which will tell you which line is causing the error.  It definitely looks like you are referencing Post before it is defined.

**Comment by clthck** [comment]
**Full Trace**

```
** Invoke annotate (first_time)
** Execute annotate
rake aborted!
NameError: uninitialized constant Post
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/extensions/inflector.rb:146:in `constantize'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/extensions/inflector.rb:146:in `module_eval'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-4.33.0/lib/sequel/extensions/inflector.rb:146:in `constantize'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-annotate-1.0.0/lib/sequel/annotate.rb:15:in `block in annotate'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-annotate-1.0.0/lib/sequel/annotate.rb:13:in `each'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-annotate-1.0.0/lib/sequel/annotate.rb:13:in `annotate'
/Volumes/WORKS/Web Applications/herokuapps/bone-falcon/lib/tasks/annotate.rake:4:in `block in <top (required)>'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/Users/clthck/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/Users/clthck/.rbenv/versions/2.3.0/bin/rake:23:in `load'
/Users/clthck/.rbenv/versions/2.3.0/bin/rake:23:in `<main>'
Tasks: TOP => annotate
```

**Comment by clthck** [comment]
I know Post class is not loaded before rake task, so I tried inserting `require 'app/models/post'`, but it then threw another error, indicating could not load such file `app/models/post.rb`. What is the proper way to resolve this?

**Comment by jeremyevans** [comment]
If I had to guess, the require fails because the `app/models/post.rb` file depends on something else that isn't being loaded.  If you are using Rails or another web framework, try loading the environment for the application first before calling `Sequel::Annotate.annotate`.

**Comment by clthck** [comment]
Can you just make a default rake task for this gem, like `annotate` gem for ActiveRecord? so that other devs don't have to create their own task.

**Comment by jeremyevans** [comment]
There is no one task that will work for all cases.  You are probably assuming that everyone using this is using Rails, which isn't the case.  None of the applications I use this in use Rails.  The best I can do is provide an example rake task that shows how it can be used, which developers can customize to fit their application.  I'm sorry you are unable to get this to work, but it appears to be due to the fact that you don't understand how your application/framework works, not due to problems in this library.  As this doesn't appear to be a bug, I'm closing this now.
