### ISSUE TITLE
Add an option to limit line length

### ISSUE THREAD

**Issue by cbrwizard** [jeremyevans/sequel-annotate#3]
Hey, good job!
One thing to add though: can you please add a line length limit option so that annotation lines do not get too long?
For example, I lint my Ruby code so that lines do not have a length larger than 80. Annotations by this gem might sometimes add pretty long lines of comments.
I wish long lines added by this gem could have been automatically separated into multiple lines when there is a line length limit. Of course, I can do that by hand, but it's much better to have it automated.

**Comment by jeremyevans** [comment]
I'm not sure there's a good way to do that that handles all cases correctly and still provides reasonable looking output. However, I would consider a pull request that adds such support.  As this isn't a bug, I'm closing this now.
