### ISSUE TITLE
Annotation duplicated when custom wrapped

### ISSUE THREAD

**Issue by harpocrates12** [jeremyevans/sequel-annotate#6]
When manually wrapping the annotation around further comments (e.g. to bypass lint line length limitation)

```
# Wrap open
# Annotations
# Wrap close
```

rerunning the annotation code will re-append the annotation

```
# Wrap open
# Annotations
# Wrap close
# Wrap open
# Annotations
# Wrap close
```

Any way to avoid this? Is there a wrapping mechanism built in the gem?

**Comment by jeremyevans** [comment]
sequel-annotate does not offer direct support for this.  You'll need to call `Sequel::Annotate#schema_comment` and handle the replacement in the file manually in that case.
