### ISSUE TITLE
namespace doesn't working

### ISSUE THREAD

**Issue by alekseyl-aurea** [jeremyevans/sequel-annotate#8]
looks like you forget to update version or gem in rubygems

**Comment by alekseyl-aurea** [comment]
Yeah, you pushed it in repo in june, and last gem update was at april

**Comment by jeremyevans** [comment]
There are nicer ways to ask for a new gem release :)  You shouldn't expect that improvements in the repository in any project will be in the latest official release.  That being said, I can release a new version later today.

**Comment by alekseyl-aurea** [comment]
) OK thanks a lot ) +1 star for your work!

**Comment by jeremyevans** [comment]
Version 1.3.0 released!
